[AI-32] Add option for custom OpenAI-compatible endpoint
stadtwerk/ai_chatgpt_web_fork pull request #1
Opened 2024-06-21 09:06 UTC by betschki

This adds the a new input field in the API settings for an OpenAI-compatible base URI, which will allow us to use open source models hosted on our own infrastructure.

What should be noted is that there are hard-coded values in some files, which are a workaround to avoid bigger refactoring, which is currently out of scope for our ticket.

2024-06-26 11:47 UTC, timlohse1104 requested changes

2024-06-26 11:47 UTC, timlohse1104 commented on src/lib/Home.svelte
> +  $: apiKey = $apiKeyStorage
Very interesting that the indentation wasnt set beforce your changes.

2024-06-26 11:47 UTC, timlohse1104 commented on src/lib/Models.svelte
> +    if (typeof model !== 'string') {
Is this check necessary? We are in a script tag lang="ts" and model seems to be of type Model which under the hood is:

export const supportedChatModels : Record<string, ModelDetail> 

Do i get it right that it will never be a string?

2024-06-26 11:47 UTC, timlohse1104 commented on src/lib/Models.svelte
> +    if (typeof model !== 'string') {
Ah i see in Chat.svelte e.g. the input param can be a string.

2024-06-26 11:47 UTC, timlohse1104 commented on src/lib/Models.svelte
> +      return result
Origin logic cached the result in tpCache and we don't do it. Is this correct?

2024-06-26 11:47 UTC, timlohse1104 commented on src/lib/Storage.svelte
> +    const endpoint = get(globalStorage).openAiEndpoint || apiBaseUriFromEnv || 'https://api.openai.com'
I would move the openai fallback url as fallback in const declaration in row 17 above as this would be a double fallback which can be hard to read.

2024-06-26 11:47 UTC, timlohse1104 commented on src/lib/Settings.svelte
I do not see any ImplicitAny rule in tsconfig files but my IDE shows errors in nearly any file.

2024-06-26 11:47 UTC, timlohse1104 commented on src/lib/providers/openai/models.svelte
> +export const fallbackModelDetail = {
Do we want to add the currently used model name "openchat-3.5-0106.Q5_K_M.gguf" ?

2024-06-27 08:23 UTC, betschki commented on src/lib/Models.svelte
> +      return result
I have decided against the cache for simplification. In my eyes, the payoff for a potential cache doesn't make much sense here. It's a tiny API request that takes milliseconds – and it doesn't cost us anything (neither on OpenAI, nor on our own infrastructure).

Caching is great, but caching just for the sake of caching is a bit useless, in my eyes 🙃

2024-06-27 08:24 UTC, betschki commented on src/lib/Storage.svelte
> +    const endpoint = get(globalStorage).openAiEndpoint || apiBaseUriFromEnv || 'https://api.openai.com'
Very good point, thank you!

2024-06-27 08:27 UTC, betschki commented
@timlohse1104 made the changes you requested – please have another final look before merging :)

2024-08-02 10:40 UTC, timlohse1104 approved these changes

2024-08-02 10:40 UTC, merged